#!/bin/sh
# /etc/init.d/vega-pppd: set up the vega-ppp server
### BEGIN INIT INFO
# Provides:          vega-ppp
# Required-Start:    $remote_fs $syslog $network $time
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin

. /lib/lsb/init-functions

if test -f /etc/default/vega-ppp; then
    . /etc/default/vega-ppp
fi

if [ -z "$VEGA_PPPD_OPTS" ]; then
  VEGA_PPPD_OPTS="-c /etc/vega-ppp.conf"
fi

case "$1" in
  start)
	log_daemon_msg "Starting IPoE/PPtP/L2TP/SSTP/PPPoE server" "vega-pppd"
	if start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/vega-pppd -- -d -p /var/run/vega-pppd.pid $VEGA_PPPD_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
  ;;
  restart)
	log_daemon_msg "Restarting IPoE/PPtP/L2TP/SSTP/PPPoE server" "vega-pppd"
	start-stop-daemon --stop --quiet --oknodo --retry 180 --pidfile /var/run/vega-pppd.pid
	if start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/vega-pppd -- -d -p /var/run/vega-pppd.pid $VEGA_PPPD_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
  ;;

  stop)
	log_daemon_msg "Stopping IPoE/PPtP/L2TP/SSTP/PPPoE server" "vega-pppd"
	start-stop-daemon --stop --quiet --oknodo --retry 180 --pidfile /var/run/vega-pppd.pid
	log_end_msg 0
  ;;

  status)
	status_of_proc /usr/sbin/vega-pppd "vega-pppd"
  ;;
  *)
    log_success_msg "Usage: /etc/init.d/vega-ppp {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0
